#!/bin/bash
#Actualizar canales de televisión

VERSION="1.0.0"
CANALES="/home/$USER/.local/tv.mhyst/tv.conf"
UCANALES="/tmp/tv.conf"

function getURL() {
        local canal="$1"
	    
	        local url="${canal##*|}"
		    url=$(tr -d '\n' <<< "$url")
		        echo "$url"
}

function getNombre() {
        local canal="$1"

	    local nombre="${canal%|*}"
	        echo "$nombre"
}

function downloadConfig() {
    wget -O "$UCANALES" https://raw.githubusercontent.com/mhyst/spaintv/master/tv.conf > /dev/null 2>&1
    return $?
}

echo "tvupdate version $VERSION - Copyleft (GPL v3) Julio Serrano 2019"
echo "Actualizar canales de televisión desde el repositorio."
echo

echo "Descargando actualización..."
echo
downloadConfig
if [[ $? > 0 ]]; then
    echo "ERROR: Fallo al descargar la actualización"
    exit 1
fi

diff "$CANALES" "$UCANALES" 2>&1
if [[ $? == 0 ]]; then
    echo "No hay cambios"
    echo "Saliendo..."
    exit 1
fi

readarray canales < "$CANALES"
readarray ucanales < "$UCANALES"

echo "Inicializando archivo de configuración..."
echo
echo "" > /tmp/utv.conf
echo "Revisando cambios:"
echo "------------------"

for canal in "${canales[@]}"; do
    nombre=$(getNombre "$canal")
    url=$(getURL "$canal")

    echo -e "$nombre... \c"
    encontrado=false
    for ucanal in "${ucanales[@]}"; do
	unombre=$(getNombre "$ucanal")
	uurl=$(getURL "$ucanal")

	if [[ $nombre == $unombre ]]; then
	    encontrado=true
	    if [[ $url != $uurl ]]; then
		echo "Actualizado!"
		url=$uurl
	    else
		echo "Sin cambios"
	    fi
	    echo "$nombre|$url" >> /tmp/utv.conf
	fi
    done
    if ! $encontrado; then
	echo "No presente"
	echo "$nombre|$url" >> /tmp/utv.conf
    fi
done

echo
echo "Buscando nuevos canales:"
echo "------------------------"
for ucanal in "${ucanales[@]}"; do
    unombre=$(getNombre "$ucanal")
    uurl=$(getURL "$ucanal")

    encontrado=false
    for canal in "${canales[@]}"; do
	nombre=$(getNombre "$canal")

	if [[ $unombre == $nombre ]]; then
	    encontrado=true
	fi
    done

    if ! $encontrado; then
	echo "Nuevo canal: $unombre"
	echo "$unombre|$uurl" >> /tmp/utv.conf
    fi
done
echo
echo -e "Seleccionando la nueva configuración... \c"
mv "$CANALES" "${CANALES}$(date +%s)"
mv "$UCANALES" "$CANALES"
echo "Completado"
